# Generated by Django 3.1.1 on 2020-10-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='ListName',
        ),
    ]
